// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SearchFunctionality.DataContext.Models;

public partial class airline_dbContext : DbContext
{
    public airline_dbContext(DbContextOptions<airline_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Airport> Airport { get; set; }

    public virtual DbSet<Flight> Flight { get; set; }

    public virtual DbSet<RegisteredUsers> RegisteredUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Airport>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("airport_id_pi")
                .IsClustered(false);
        });

        modelBuilder.Entity<Flight>(entity =>
        {
            entity.HasKey(e => e.Id)
                .HasName("flight_id_pi")
                .IsClustered(false);

            entity.Property(e => e.ArrivalTime).HasColumnType("datetime");
            entity.Property(e => e.DepartureTime).HasColumnType("datetime");

            entity.HasOne(d => d.FromAirport).WithMany(p => p.FlightFromAirport)
                .HasForeignKey(d => d.FromAirportId)
                .HasConstraintName("flight_airportidairport_fk");

            entity.HasOne(d => d.ToAirport).WithMany(p => p.FlightToAirport)
                .HasForeignKey(d => d.ToAirportId)
                .HasConstraintName("flight_toairportidairport_fk");
        });

        modelBuilder.Entity<RegisteredUsers>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}