// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SearchFunctionality.DataContext.Models;

public partial class Airport
{
    public int Id { get; set; }

    public string AirportName { get; set; }

    public string Code { get; set; }

    public virtual ICollection<Flight> FlightFromAirport { get; set; } = new List<Flight>();

    public virtual ICollection<Flight> FlightToAirport { get; set; } = new List<Flight>();
}