// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SearchFunctionality.DataContext.Models;

public partial class Flight
{
    public int Id { get; set; }

    public int? FromAirportId { get; set; }

    public int? ToAirportId { get; set; }

    public string FlightNumber { get; set; }

    public DateTime? DepartureTime { get; set; }

    public DateTime? ArrivalTime { get; set; }

    public long? Price { get; set; }

    public virtual Airport FromAirport { get; set; }

    public virtual Airport ToAirport { get; set; }
}